name: lleaves
channels:
  - conda-forge
  - nodefaults
dependencies:
  # runtime deps
  - llvmlite
  - numpy
  # testing
  - pytest
  - hypothesis
  - lightgbm
  - pre-commit
  - pyarrow
  - pandas
  # benchmarking
  - treelite
  # onnxmltools currently broken for categorical models, install from master
  # - onnxmltools
  - onnxruntime
  - seaborn
  # development
  - sphinx
  - sphinx_rtd_theme
  - numpydoc
  - sphinxcontrib-apidoc
  - pip
  - pip:
      - "git+git://github.com/onnx/onnxmltools@master"
