name: lleaves
channels:
  - conda-forge
  - defaults
dependencies:
  - llvmlite
  - pytest
  - hypothesis
  - lightgbm
  - numpy
  - pre-commit
  - treelite
  - onnxmltools
  - onnxruntime
  - pandas
  - seaborn
