name: lleaves
channels:
  - conda-forge
  - defaults
dependencies:
  # runtime deps
  - llvmlite
  - numpy
  # testing
  - pytest
  - hypothesis
  - lightgbm
  - pre-commit
  - pyarrow
  - pandas
  # benchmarking
  - treelite
  # - onnxmltools
  - onnxruntime
  - seaborn
  # development
  - sphinx
  - sphinx_rtd_theme
  - pip
  - pip:
      - "git+git://github.com/janjagusch/onnxmltools@fix-nodes-values"
